language: ruby
sudo: false
cache: bundler
rvm:
  - 2.0
  - 2.1
  - 2.2
env:
  - RAILS_VERSION=3.2
  - RAILS_VERSION=4.1
  - RAILS_VERSION=4.2
  - ORM=active_record
allow_failures:
  - ORM=mongoid
  - rvm: 2.2
services:
  - mongodb
